"""addede a teacher category to the user model, and created the profile model

Revision ID: 2bd64fb21839
Revises: 6d299acec44b
Create Date: 2026-03-15 21:12:15.818890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bd64fb21839'
down_revision: Union[str, Sequence[str], None] = '6d299acec44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'teacher_category',
               existing_type=postgresql.ENUM('pending', 'approved', 'starter', 'paid_courses', 'popular', 'vip', name='teachercategory'),
               comment=None,
               existing_comment='Only applicable for teachers, determines their status and privileges',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'teacher_category',
               existing_type=postgresql.ENUM('pending', 'approved', 'starter', 'paid_courses', 'popular', 'vip', name='teachercategory'),
               comment='Only applicable for teachers, determines their status and privileges',
               existing_nullable=True)
    op.drop_table('profiles')
    # ### end Alembic commands ###
