"""added a teacher category to the user model

Revision ID: 6d299acec44b
Revises: 664d05176fc4
Create Date: 2026-03-13 01:25:47.513974

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d299acec44b"
down_revision: Union[str, Sequence[str], None] = "664d05176fc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    teacher_category_enum = postgresql.ENUM(
        "pending",
        "approved",
        "starter",
        "paid_courses",
        "popular",
        "vip",
        name="teachercategory",
    )
    teacher_category_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "teacher_category",
            sa.Enum(
                "pending",
                "approved",
                "starter",
                "paid_courses",
                "popular",
                "vip",
                name="teachercategory",
            ),
            nullable=True,
            comment="Only applicable for teachers, determines their status and privileges",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "teacher_category")
    # ### end Alembic commands ###
